platform :ios, '9.0'

target 'Genji' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'

  pod 'FirebaseUI/Auth'
end
