default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release do
      increment_build_number
      build_app(scheme: "Genji")
      upload_to_app_store
  end
  lane :bump do
      increment_version_number
  end
end
